# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

def main_sources
pod 'RxSwift',     '~> 4.0'
pod 'RxCocoa',     '~> 4.0'
end

target 'ViperDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  main_sources
  # Pods for ViperDemo

  target 'ViperDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxTest', '~> 4.0'
  end

end
